#include "../core/http_tls.h"

namespace fry_http {

// Mozilla root CA bundle, embedded via board_build.embed_files (platformio.ini [esp32common],
// inherited by esp32/esp32s3/esp32c3/esp32_lab) from data/cert/x509_crt_bundle.bin. Generated by
// data/cert/gen_crt_bundle.py from the FULL Mozilla root store (not a hand-picked subset — an
// earlier hand-picked 3-root version of this bundle was caught before shipping: it missed the
// roots github.com and release-assets.githubusercontent.com/objects.githubusercontent.com
// actually terminate their chains at, which would have bricked OTA fleet-wide since these CAs
// are mid-rotation). See that script's header for the exact source files, hashes, and the two
// supplemental roots (ISRG Root YE/YR) added because they're too new for Mozilla's root program
// yet but are what some of these hosts' chains terminate at.
//
// Symbol name follows PlatformIO/GNU objcopy's binary-embed convention: the embedded file's
// project-relative path as given in board_build.embed_files, with every non-alphanumeric
// character (path separators, the dot before the extension) replaced by '_'.
extern const uint8_t x509_crt_bundle_start[] asm("_binary_data_cert_x509_crt_bundle_bin_start");

bool beginHttpsUrl(HTTPClient& http, WiFiClientSecure& sec, const String& url) {
  sec.setCACertBundle(x509_crt_bundle_start);

  if (!http.begin(sec, url)) return false;
  http.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
  http.setRedirectLimit(5);
  return true;
}

}  // namespace fry_http
